Cloud hosted adjustments
OpenLiberty/draft-guide-microprofile-jwt pull request #163
Opened 2021-04-21 20:47 UTC by AustinSeto

Adjust some wordings for the cloud hosted version of the guide

2021-04-21 21:38 UTC, gkwan-ibm requested changes
@AustinSeto would you not delete the .travis.yml.disabled for now? We will remove it later.

2021-04-21 21:43 UTC, gkwan-ibm requested changes

2021-04-21 21:43 UTC, gkwan-ibm commented on README.adoc
> +You get an empty response since you don't have access because you didn't supply a valid JWT with the request.
`since` and `because` in one statement looks not right

2021-04-22 16:07 UTC, dmuelle requested changes
one typo to fix

2021-04-22 16:07 UTC, dmuelle commented on README.adoc
> +There response is empty because you don't have access.
There response is empty
--->
The response is empty

2021-04-22 21:30 UTC, dmuelle approved these changes
LGTM

2021-04-23 13:01 UTC, gkwan-ibm approved these changes

2021-04-23 13:01 UTC, merged