Mpjwt property change
OpenLiberty/draft-guide-microprofile-jwt pull request #173
Opened 2021-07-27 13:50 UTC by rutavshah

2021-07-27 18:35 UTC, gkwan-ibm requested changes
hi @rutavshah 
- [x] suggest to change "config property" to "property"
- [x] check the content with https://openliberty.io/blog/2021/03/26/MP-JWT-1.2.html
- [ ] make sure end-to-end and cloud-hosted pass

2021-08-06 13:51 UTC, gkwan-ibm commented
hi @rutavshah 
- [ ] Would you add a statement to mention `.claim("aud", "conferenceService")` at the last paragraph of  the **Creating a client to access the secure system service** section?

2021-08-10 13:35 UTC, teddyjtorres commented on finish/frontend/src/main/java/io/openliberty/guides/frontend/LoginBean.java
> +                         .claim("aud", "conferenceService")
Please rename "conferenceService" to "systemService" since the System Service is the intended audience. This is for consistency with the guide section https://openliberty.io/guides/microprofile-jwt.html#what-youll-learn.

2021-08-10 13:36 UTC, teddyjtorres commented on finish/system/src/main/webapp/META-INF/microprofile-config.properties
> +mp.jwt.verify.audiences=conferenceService, adminServices
Please rename "conferenceService" to "systemService" and remove adminServices since the System Service is the intended audience. This is for consistency with the guide section https://openliberty.io/guides/microprofile-jwt.html#what-youll-learn.

2021-08-10 13:36 UTC, teddyjtorres commented on finish/system/src/test/java/it/io/openliberty/guides/system/util/JwtBuilder.java
> +            .put("aud", "conferenceService")
Please rename "conferenceService" to "systemService" since the System Service is the intended audience. This is for consistency with the guide section https://openliberty.io/guides/microprofile-jwt.html#what-youll-learn.

2021-08-10 13:36 UTC, teddyjtorres commented on start/frontend/src/main/java/io/openliberty/guides/frontend/LoginBean.java
> +                         .claim("aud", "conferenceService")
Please rename "conferenceService" to "systemService" since the System Service is the intended audience. This is for consistency with the guide section https://openliberty.io/guides/microprofile-jwt.html#what-youll-learn.

2021-08-10 13:37 UTC, teddyjtorres commented on start/system/src/test/java/it/io/openliberty/guides/system/util/JwtBuilder.java
> +            .put("aud", "conferenceService")
Please rename "conferenceService" to "systemService" since the System Service is the intended audience. This is for consistency with the guide section https://openliberty.io/guides/microprofile-jwt.html#what-youll-learn.

2021-08-10 13:41 UTC, teddyjtorres requested changes
Thank you for the changes. Please rename the value for the audience claims for consistency with the guide. Thanks!

2021-08-24 13:40 UTC, teddyjtorres approved these changes

2021-08-24 19:31 UTC, priyyanshi commented
Peer reviewed, LGTM.

2021-08-24 19:32 UTC, priyyanshi approved these changes

2021-08-25 20:55 UTC, ManasiGandhi requested changes
A few edit suggestions

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +The `aud` claim  is used to specify the audience that the JWT is intended for.
Change,
"The `aud` claim  is used to specify the audience that the JWT is intended for."
to,
"The `aud` claim is used to specify the audience that the JWT is intended for."
Remove extra space between "claim" and  "is"

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +| [hotspot=header file=0]`mp.jwt.token.header`  | Allows you to control the HTTP request header which is expected to contain a JWT token. You can specify either Authorization (default) or Cookie valu
Change,
"Allows you to control the HTTP request header which is expected to contain a JWT token. You can specify either Authorization (default) or Cookie values."
to,
"With this property, you can control the HTTP request header, which is expected to contain a JWT. You can either specify Authorization, by default, or the Cookie values."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +| [hotspot=cookie file=0]`mp.jwt.token.cookie` | Allows you to specify the name of the cookie which is expected to contain a JWT token. The default value is Bearer if not specified.
Change,
"Allows you to specify the name of the cookie which is expected to contain a JWT token. The default value is Bearer if not specified."
to,
"Specifies the name of the cookie, which is expected to contain a JWT token. The default value is Bearer."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +| [hotspot=audiences file=0]`mp.jwt.verify.audiences` |  Allows you to create list of allowable audience (aud) values. At least one of these must be found in the claim. Previously, this had to be con
Change,
"Allows you to create list of allowable audience (aud) values. At least one of these must be found in the claim. Previously, this had to be configured in the server.xml file."
to,
"With this property, you can create a list of allowable audience (aud) values. At least one of these values must be found in the claim. Previously, this configuration was included in the `server.xml` file."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +| [hotspot=location file=0]`mp.jwt.decrypt.key.location` | Allows you to specify the location of the Key Management Key. It is a Private key used to decrypt the Content Encryption Key, which is then
Change,
"Allows you to specify the location of the Key Management Key. It is a Private key used to decrypt the Content Encryption Key, which is then used to decrypt the JWE ciphertext. This private key must correspond to the public key that is used to encrypt the Content Encryption Key."
to,
"With this property, you can specify the location of the Key Management key. It is a Private key that is used to decrypt the Content Encryption key, which is then used to decrypt the JWE ciphertext. This private key must correspond to the public key that is used to encrypt the Content Encryption key."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +| [hotspot=algorithm file=0]`mp.jwt.verify.publickey.algorithm` | Allows you to control the Public Key Signature Algorithm that is supported by the MicroProfile JWT endpoint. The default value is RSA
Change,
"Allows you to control the Public Key Signature Algorithm that is supported by the MicroProfile JWT endpoint. The default value is RSA256 if not specified. Previously, this had to be configured in the server.xml file."
to,
"With this property, you can control the Public Key Signature Algorithm that is supported by the MicroProfile JWT endpoint. The default value is RSA256. Previously, this configuration was included in the `server.xml` file."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +// The [hotspot=header file=0]`mp.jwt.token.header` property allows you to control the HTTP request header which is expected to contain a JWT token. You can specify either Authorization (default) or
Change,
"The [hotspot=header file=0]`mp.jwt.token.header` property allows you to control the HTTP request header which is expected to contain a JWT token. You can specify either Authorization (default) or Cookie values."
to,
"With the [hotspot=header file=0]`mp.jwt.token.header` property, you can control the HTTP request header, which is expected to contain a JWT. You can either specify Authorization, by default, or the Cookie values."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +// The [hotspot=cookie file=0]`mp.jwt.token.cookie` property allows you to specify the name of the cookie which is expected to contain a JWT token. The default value is Bearer if not specified.
Change,
"The [hotspot=cookie file=0]`mp.jwt.token.cookie` property allows you to specify the name of the cookie which is expected to contain a JWT token. The default value is Bearer if not specified."
to,
"The [hotspot=cookie file=0]`mp.jwt.token.cookie` property specifies the name of the cookie, which is expected to contain a JWT token. The default value is Bearer."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +// The [hotspot=audiences file=0]`mp.jwt.verify.audiences` property allows you to create list of allowable audience (aud) values. At least one of these must be found in the claim. Previously, this ha
Change,
"The [hotspot=audiences file=0]`mp.jwt.verify.audiences` property allows you to create list of allowable audience (aud) values. At least one of these must be found in the claim. Previously, this had to be configured in the server.xml file."
to,
"With the [hotspot=audiences file=0]`mp.jwt.verify.audiences` property, you can create a list of allowable audience (aud) values. At least one of these values must be found in the claim. Previously, this configuration was included in the `server.xml` file."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +// The [hotspot=location file=0]`mp.jwt.decrypt.key.location` property allows you to specify the location of the Key Management Key. It is a Private key used to decrypt the Content Encryption Key, wh
Change,
"The [hotspot=location file=0]`mp.jwt.decrypt.key.location` property allows you to specify the location of the Key Management Key. It is a Private key used to decrypt the Content Encryption Key, which is then used to decrypt the JWE ciphertext. This private key must correspond to the public key that is used to encrypt the Content Encryption Key."
to,
"With the [hotspot=location file=0]`mp.jwt.decrypt.key.location` property, you can specify the location of the Key Management key. It is a Private key that is used to decrypt the Content Encryption key, which is then used to decrypt the JWE ciphertext. This private key must correspond to the public key that is used to encrypt the Content Encryption key."

2021-08-25 20:55 UTC, ManasiGandhi commented on README.adoc
> +// The [hotspot=algorithm file=0]`mp.jwt.verify.publickey.algorithm` property allows you to control the Public Key Signature Algorithm that is supported by the MicroProfile JWT endpoint. The default
Change,
"The [hotspot=algorithm file=0]`mp.jwt.verify.publickey.algorithm` property allows you to control the Public Key Signature Algorithm that is supported by the MicroProfile JWT endpoint. The default value is RSA256 if not specified. Previously, this had to be configured in the server.xml file."
to,
"With the [hotspot=algorithm file=0]`mp.jwt.verify.publickey.algorithm` property, you can control the Public Key Signature Algorithm that is supported by the MicroProfile JWT endpoint. The default value is RSA256. Previously, this configuration was included in the `server.xml` file."

2021-08-26 18:43 UTC, ManasiGandhi approved these changes

2021-08-26 20:46 UTC, gkwan-ibm approved these changes

2021-08-26 21:47 UTC, teddyjtorres commented on README.adoc
> +| [hotspot=algorithm file=0]`mp.jwt.verify.publickey.algorithm` | With this property, you can control the Public Key Signature Algorithm that is supported by the MicroProfile JWT endpoint. The defaul
Please change RSA256 to RS256

2021-08-26 21:48 UTC, teddyjtorres commented on finish/system/src/main/webapp/META-INF/microprofile-config.properties
> +mp.jwt.verify.publickey.algorithm=RSA256
Please change RSA256 to RS256

2021-08-26 22:00 UTC, gkwan-ibm requested changes
update RAS246 to RS256

2021-08-27 18:41 UTC, gkwan-ibm approved these changes

2021-08-27 18:42 UTC, merged